# Generated by Django 3.2.17 on 2023-02-15 20:29

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('restapisapp', '0003_alter_books_pages'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='Books',
            new_name='Book',
        ),
    ]
