# Generated by Django 3.2.17 on 2023-02-21 08:39

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('restapisapp', '0006_auto_20230220_2251'),
    ]

    operations = [
        migrations.CreateModel(
            name='Playlist',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('title', models.CharField(blank=True, max_length=100, null=True)),
                ('artist', models.CharField(blank=True, max_length=100, null=True)),
                ('album', models.CharField(blank=True, max_length=100, null=True)),
                ('user_id', models.IntegerField()),
            ],
        ),
    ]
